### ISSUE TITLE
New and Improved Frontside Actions v2

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/actions#68]
## Motivation

I'm in the process of rewriting all of our actions in Typescript in preparation of releasing `v2`.

| Name | PR |
| -- | -- | 
| `publish-pr-preview` | #65, #69, #70, #71 |
| `synchronize-npm-tags` | #66 |
| `synchronize-with-npm` | #67 |

## TODOs
- [x] ~I think we should also discuss the idea of renaming our actions - mainly `synchronize-with-npm` but might as well rename the other ones too:~
  | Old Name | New Name |
  | -- | -- |
  | `synchronize-with-npm` | `publish-releases` |
  | `synchronize-npm-tags` | `synchronize-tags`? |
  | `publish-pr-preview` | `publish-previews` |
- [x] ~We have the [`yarn`](https://github.com/thefrontside/actions/tree/main/yarn) action which we created in order to fail a workflow if there are any warnings during `yarn install`. I don't think we need to keep that as a separate action. If we really wanted to incorporate that, we could do so within the other actions. Is it okay to omit this one from v2?~
  - [x] Delete [yarn action](https://github.com/thefrontside/actions/tree/v1/yarn) from v2 and update table at root readme #70
- [x] Push current `main` branch to `v2` to prevent any conflicts to workflows that are calling actions from the `main` branch
- [x] Change base branch of remaining PRs to `v2`
- [x] ~Once all actions are refactored, update all frontside projects to use `@v2`~ Do this on a need-to basis
- [x] Update readmes to use v2 (the readmes are currently instructing to call the actions from `main` branch) #70
- [x] Delete `main` branch
  - [x] These repositories need to update their workflows to migrate from `main` to `v2` and we'll be able to delete the `main` branch:
    - [x] [`thefrontside/element-is-visible` #5](https://github.com/thefrontside/element-is-visible/pull/5)
    - [x] [`thefrontside/javascript` #50](https://github.com/thefrontside/javascript/pull/50)
    - [x] [`thefrontside/performance-api` #6](https://github.com/thefrontside/performance-api/pull/6)
    - [x] [`thefrontside/microstates` #426](https://github.com/thefrontside/microstates/pull/426)
      - If you scroll through [here](https://github.com/search?q=org%3Athefrontside+thefrontside%2Factions&type=code) you should see they've all been updated (if the four PRs above have been merged)

**Comment by taras** [comment]
Is this finished now?

**Comment by minkimcello** [comment]
#66, #67, #70, and #76 need to be approved

**Comment by minkimcello** [comment]
@taras i just assigned you and jacob to this issue (and #76) so that it's on your radar as they describe and link to all the PRs related to this refactor
